/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/sim/scenarios': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              scenarios: {
                meta: {
                  name: string;
                  description: string;
                  targets: string[];
                  parameter_schema: Record<string, unknown>;
                  safety_limits: Record<string, unknown>;
                };
              }[];
            };
          };
        };
      };
    };
  };
  '/api/sim/status': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': {
              active_scenarios: {
                name: string;
                enabled_at: string;
                expires_at: string | null;
                parameters: Record<string, unknown>;
              }[];
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Scenario: {
      meta: {
        name: string;
        description: string;
        targets: string[];
        parameter_schema: Record<string, unknown>;
        safety_limits: Record<string, unknown>;
      };
    };
    ActiveScenario: {
      name: string;
      enabled_at: string;
      expires_at: string | null;
      parameters: Record<string, unknown>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

